# This is tied to app/states/config_reader.rb parser


# general config

general:
  mongo_batch_insert_size:                  1000
  video_localization_path:                  '/sftp/sftpuser/uploads'
  localization_filename:                    'localizations.json'
  localization_image_folder:                'images'
  localization_thumbnail_folder:            'thumbnails'

detectable_metrics:
  # event score decay
  # note: the size of the weight array must be the same as number of decay seconds
  event_score_time_decay_seconds:                      5
  # note: decay weights are made symmetric during metrics creation, 
  # so the decay array needs to have increasing values
  event_score_time_decay_weights:                      [0, 0, 0, 0, 1.0]
  #[0, 0.05, 0.1, 0.25, 0.6]
  # sliding window - scores
  # need to average scores only through one second worth of frames
  sliding_window_size_seconds_scores:                  1
  sliding_window_decay_weights_scores:                 [0, 0, 0, 0, 1.0]
  # quadrants
  quadrants_num_cols:                                  3
  quadrants_num_rows:                                  3
  # the center weight is always unity - all other quadrant weights are smaller than it
  quadrants_center_weight:                             1.0
  quadrants_corner_weight:                             0.25
  quadrants_non_corner_edge_weight:                    0.5

det_group_metrics:
  # sliding window - temporal crowding
  sliding_window_size_seconds_temporal_crowding:       5
  sliding_window_decay_weights_temporal_crowding:      [0, 0, 0, 0, 1.0]
  # crowding weights
  spatial_crowding_weight:                             0
  temporal_crowding_weight:                            0
  # brand effectiveness weights
  be_det_group_crowding:                               0
  be_visual_saliency:                                  0
  be_timing_effectiveness:                             0
  be_spatial_effectiveness:                            1.0

