# This is tied to app/states/config_reader.rb parser

mongo_batch_insert_size:                  100
video_localization_path:                  '/sftp/sftpuser/uploads'
localization_image_folder:                'images'
localization_thumbnail_folder:            'thumbnails'
video_folder:                             'videos'
short_clip_folder:                        'clips'
max_short_clips:                          100
num_short_clips_to_destroy:               25
