# This is tied to app/states/config_reader.rb parser

mongo_batch_insert_size:                  500
video_localization_path:                  '/sftp/sftpuser/uploads'
localization_image_folder:                'images'
localization_thumbnail_folder:            'thumbnails'
