# put in SMTP mail information
development: &development
  address: smtp.gmail.com
  port: 587
  user_name: zigvuinc.test@gmail.com
  password: thisisalongpassword

test:
  <<: *development

production:
  address: smtp.zoho.com
  port: 587
  user_name: accounts@zigvu.com
  password: thisisalongpassword

local:
  <<: *development
